name: Extract iFlows from Tenant to GitHub
on:
  schedule:
    - cron: '0 22 * * 1-5' # Runs automatically every weekday at 10 PM UTC
  workflow_dispatch:      # Allows you to click a button in GitHub to run it manually

jobs:
  sync-tenant-to-git:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest # FlashPipe container tool
    steps:
      - uses: actions/checkout@v4
      
      - name: Sync Integration Packages
        env:
          GC_OAUTH_CLIENT_ID: "sb-90cceda5-c40c-4eaa-a21b-e7cb362936ad!b658509|it!b55215"
          GC_OAUTH_CLIENT_SECRET: "a67e15f7-bb6b-4b3b-9bca-5b4b3fb18275$T1BqakvlmLiVp0UlBFgaMcbSv5VuERaqowHtKgIERrQ="
          GC_OAUTH_TOKEN_URL: ${{ secrets.CPI_TOKEN_URL }}
          GC_TENANT_TMN_URL: "https://90cfb10ftrial.integrationsuite-trial01.cfapps.us10-001.hana.ondemand.com/" # e.g., your-tenant.itspaces.hci.ext.sap.com
          GC_WORKSPACE: ${{ github.workspace }}
        run: |
          # Command to point to your integration package and pull down files
          flashpipe sync-tenant-to-git --package-ids "Test_Package"
