stages:
  Prepare:
    execute:
      - "./.pipeline/create-package.sh"

  Upload:
    integrationArtifactUpload:
      cpiApiServiceKeyCredentialsId: "sapiskey"
      packageId: "DemoPackage"
      integrationFlowId: "Demo_iflow"
      filePath: "integration-suite-content/Demo_Package/Demo_iflow/Demo_iflow.zip"

  Deploy:
    integrationArtifactDeploy:
      cpiApiServiceKeyCredentialsId: "sapiskey"
      integrationFlowId: "Demo_iflow"
