general:
  verbose: true

stages:
  Upload:
    enabled: true

  Deploy:
    enabled: true

  'Integration Test':
    enabled: false

steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: "sapiskey"
    packageId: "DemoPackage"
    integrationFlowId: "Demo_iflow"

  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: "sapiskey"
    integrationFlowId: "Demo_iflow"
