stages:
  Prepare:
    execute:
      - "./.pipeline/create-package.sh"

  Upload:
    integrationArtifactUpload:
      cpiApiServiceKeyCredentialsId: "sapiskey"
      packageId: "Test_Package"
      integrationFlowId: "Test_Iflow"
      filePath: "integration-suite-content/Test_Package/Test_Iflow/Test_Iflow.zip"

  Deploy:
    integrationArtifactDeploy:
      cpiApiServiceKeyCredentialsId: "sapiskey"
      integrationFlowId: "Test_Iflow"
