name: Extract iFlows from Tenant to GitHub

on:
  workflow_dispatch:      # This allows you to click a button to run it manually
  schedule:
    - cron: '0 22 * * 1-5' # Runs automatically every weekday at 10 PM UTC

jobs:
  sync-tenant-to-git:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest # FlashPipe container tool
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Sync Integration Packages
        env:
          GC_OAUTH_CLIENT_ID: ${{ secrets.CPI_CLIENT_ID }}
          GC_OAUTH_CLIENT_SECRET: ${{ secrets.CPI_CLIENT_SECRET }}
          GC_OAUTH_TOKEN_URL: "90cfb10ftrial.authentication.us10.hana.ondemand.com"
          GC_TENANT_TMN_URL: "90cfb10ftrial.integrationsuite-trial01.cfapps.us10-001.hana.ondemand.com" # Replace with your TMN URL
          GC_WORKSPACE: ${{ github.workspace }}
        run: |
          flashpipe sync-tenant-to-git --package-ids "Test_Package"
